In [7]:

import numpy as np


# To compute vector length
def compute_vector_length(vector):
    return np.linalg.norm(vector)


# To compute dot product
def compute_dot_product(v1, v2):
    return np.dot(v1, v2)


#
def matrix_multi_vector(m, v):
    return np.dot(m, v)


#
def matrix_multi_matrix(m1, m2):
    return np.dot(m1, m2)


#
def inverse_matrix(m):
    return np.linalg.inv(m)

In [6]:
vector = np.array ([ -2 , 4 , 9 , 21])
result = compute_vector_length(vector)
print(round(result, 2))

23.28


In [8]:
v1 = np. array ([0 , 1 , -1 , 2])
v2 = np. array ([2 , 5 , 1 , 0])
result = compute_dot_product (v1 , v2)
print ( round (result ,2) )

4


In [12]:
x = np. array ([[1 , 2],
                [3 , 4]])

k = np. array ([1 , 2])
print (f'result:', np.dot(x, k))

result: [ 5 11]


In [13]:
x = np.array([[-1, 2], [3, -4]])

k = np.array([1, 2])
print(f"result:", np.dot(x, k))

result: [ 3 -5]


In [14]:
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])

matrix_multi_vector(m, v)

array([3, 1])

In [16]:
m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3], [6, 1], [0, -1]])


matrix_multi_matrix(m1, m2)

array([[  6,  -1],
       [-16, -10]])

In [19]:
m1 = np.eye(3)
m2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

result = m1@m2
result


array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])