In [1]:
# class Cat(self, name, color, age, state):
class Cat:
    def __init__(self, name, age, state):
        self.name = name
        self.age = age
        self.state = state

    def sleep(self):
        self.state = "ngủ"
        return self.state

Jerry = Cat("Jerry", 10, None)
print(Jerry.state)
print(Jerry.age)

Jerry.sleep()
print(Jerry.state)

None
10
ngủ


## OOP - Pytorch
### Ex 1


In [8]:
import torch
import torch.nn as nn


class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition

class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdims=True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition


data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
output


data = torch.Tensor([1, 2, 3])
my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [4]:
data = torch.Tensor ([1 , 2 , 3])
softmax_function = nn.Softmax(dim =0)
output = softmax_function(data)
assert round(output [0].item(),2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [5]:
data = torch . Tensor ([5 , 2 , 4])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [ -1]. item () , 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

In [6]:
data = torch . Tensor ([1 , 2 , 300000000])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [0]. item () , 2) == 0.0
output

tensor([0., 0., nan])

In [9]:
data = torch . Tensor ([1 , 2 , 3])
softmax_stable = SoftmaxStable ()
output = softmax_stable ( data )
assert round ( output [ -1]. item () , 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

In [3]:
from abc import ABC, abstractmethod


class Person(ABC):
    def __init__(self, name, yob):
        self._name =  name
        self._yob = yob
        
    def get_yob(self):
        return self._yob
        
        
    @abstractmethod
    def describe(self):
        pass


class Student(Person):
    def __init__(self, name, yob, grade): #student will add Grade

        super().__init__(name=name, yob=yob)
        self.__grade = grade

    def describe(self):
        print(
            f" Student - Name: {self._name} | YoB: {self._yob} | Grade: {self.__grade}"
        )


class Doctor(Person):
    def __init__(self, name, yob, specialist):  # student will add Grade

        super().__init__(name=name, yob=yob)
        self.__specialist = specialist

    def describe(self):
        print(
            f" Doctor - Name: {self._name} | YoB: {self._yob} | Specialist: {self.__specialist}"
        )


class Teacher(Person):
    def __init__(self, name, yob, subject):  # student will add Grade

        super().__init__(name=name, yob=yob)
        self.__subject = subject

    def describe(self):
        print(f" Teacher - Name: {self._name} | YoB: {self._yob} | Subject: {self.__subject}")

In [4]:
Nguyen = Student("Nguyen", 1998, 10)
Phat = Doctor('Phat', 1999, 'Crazy')
Hieu = Teacher("Hieu", 1998, 'Math')

Nguyen.describe()
Phat.describe()
Hieu.describe()

 Student - Name: Nguyen | YoB: 1998 | Grade: 10
 Doctor - Name: Phat | YoB: 1999 | Specialist: Crazy
 Teacher - Name: Hieu | YoB: 1998 | Subject: Math


In [5]:
class Ward():
    def __init__(self, name):
        self.__name = name
        self.__list_people = list()

    def add_person(self, person: Person):
        self.__list_people.append(person)

    def describe(self):
        print(f'Name: {self.__name}')
        for p in self.__list_people:
            p.describe()
            
    def count_doctor(self):
        counter = 0
        for p in self.__list_people:
            if isinstance(p, Doctor):
                counter += 1
        return counter
    
    def sort_yob(self):
        return self.__list_people.sort(key = lambda x: x.get_yob())
    
    def compute_average(self):
        counter = 0
        total_year = 0
        for p in self.__list_people:
            if isinstance(p, Teacher):
                counter += 1
                total_year += p.get_yob()
        return total_year / counter
                
        

In [6]:
w1 = Ward('Ward 1')

In [7]:
w1.add_person(Nguyen)
w1.add_person(Phat)
w1.add_person(Hieu)
w1.describe()

Name: Ward 1
 Student - Name: Nguyen | YoB: 1998 | Grade: 10
 Doctor - Name: Phat | YoB: 1999 | Specialist: Crazy
 Teacher - Name: Hieu | YoB: 1998 | Subject: Math


In [11]:
# w1.count_doctor()
w1.sort_yob()
w1.describe()
# w1.compute_average()
print(f"\nAverage year of birth (teachers): {w1.compute_average()}")

Name: Ward 1
 Student - Name: Nguyen | YoB: 1998 | Grade: 10
 Teacher - Name: Hieu | YoB: 1998 | Subject: Math
 Doctor - Name: Phat | YoB: 1999 | Specialist: Crazy

Average year of birth (teachers): 1998.0


## Ex 3

In [ ]:
class MyStack:
    def __init__(self, capacity, ) -> None:
        self.__capacity = capacity
        self.__stack = []
    
    def is_empty(self):
        
        
        

In [ ]:
class My_Stack:
    def __init__(self) -> None:
        
    